version: '3.8'

services:
  ollama:
    build: .
    deploy: 
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES all
      - NVIDIA_DRIVER_CAPABILITIES compute,utility
      - CUDA_ENABLE_TENSOR_CORES 240
    runtime: nvidia        
